project:
  type: book
  output-dir: docs

book:
  title: "Gribble Lab Manual"
  author: "Paul Gribble"
  repo-url: https://github.com/paulgribble/labmanual
  repo-actions: [edit, issue]
  page-navigation: true
  search: true
  sidebar:
    style: "docked"
  page-footer:
    left: "© 2026 Gribble Lab, released under the <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0 license</a>"
    right: "Built with <a href='https://quarto.org'>Quarto</a>"
  chapters:
    - index.qmd
    - 01_contact-information.md
    - 02_contacting-me.md
    - 03_onboarding.md
    - 04_communication.md
    - 05_lab-culture.md
    - 06_being-present.md
    - 07_general-expectations.md
    - 08_specific-expectations.md
    - 09_use-of-ai-tools.md
    - 10_individual-meetings.md
    - 11_my-feedback-to-you.md
    - 12_lab-meetings.md
    - 13_lab-rooms.md
    - 14_research-ethics.md
    - 15_software-and-computers.md
    - 16_conference-travel.md
    - 17_purchasing-and-lab-supplies.md
    - 18_equity-diversity-inclusion.md
    - 19_conflict-resolution.md
    - 20_egregious-behaviour.md
    - 21_scientific-misconduct.md
    - 22_work-life-balance.md
    - 23_well-being.md
    - 24_need-help.md
    - 25_acknowledgements.md

format:
  html:
    theme:
      light: united
      dark: [darkly, united-dark.scss]
    toc: true
    respect-user-color-scheme: true

